In [1]:
import numpy as np
my_arr = np.arange(10000000)
my_list = list(range(10000000))

In [5]:
%time for _ in range(10):my_arr2 = my_arr*2

Wall time: 139 ms


In [6]:
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

Wall time: 6.1 s


In [2]:
data = np.random.randn(2, 3)

In [3]:
data

array([[-0.47927669, -0.2404384 ,  1.30508088],
       [ 3.45101774, -0.25958147, -1.47227122]])

In [4]:
data*10

array([[ -4.79276688,  -2.40438398,  13.05080882],
       [ 34.51017741,  -2.59581472, -14.7227122 ]])

In [5]:
data+data

array([[-0.95855338, -0.4808768 ,  2.61016176],
       [ 6.90203548, -0.51916294, -2.94454244]])

In [6]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [1, 4, 5, 7.5]
arr1 = np.array(data1)
arr1

array([1. , 4. , 5. , 7.5])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [22]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [23]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [25]:
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [27]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5:8]=12

In [30]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [31]:
arr_slice = arr[5:8]

In [32]:
arr_slice

array([12, 12, 12])

In [33]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [34]:
arr_slice[:] = 64 
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[2]

array([7, 8, 9])

In [39]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
old_values = arr3d[0].copy()

In [43]:
arr3d[0]= 42 

In [44]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0] = old_values

In [46]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [49]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2d[1, :2]

array([4, 5])

In [51]:
arr2d[1]

array([4, 5, 6])

In [52]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [53]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [54]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe' ])
data = np.random.randn(7,4)

In [56]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [57]:
data

array([[ 0.416265  ,  0.27712602,  1.53009909,  0.3255302 ],
       [ 1.32618412, -0.01138557, -0.01409756,  0.5988489 ],
       [-0.00618896, -0.27795997,  0.30420328,  1.29108859],
       [-0.97699798, -0.81100512,  1.03902066, -1.40888628],
       [-0.20374692,  0.45387091,  1.59509374,  0.60522322],
       [ 1.12400473,  0.40844548,  0.95931015, -1.17977155],
       [ 1.76644748, -0.38508707,  0.34254208,  1.53624934]])

In [59]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [60]:
data[names=='Bob']

array([[ 0.416265  ,  0.27712602,  1.53009909,  0.3255302 ],
       [-0.97699798, -0.81100512,  1.03902066, -1.40888628]])

In [61]:
data[names == 'Bob', 2:]

array([[ 1.53009909,  0.3255302 ],
       [ 1.03902066, -1.40888628]])

In [62]:
data[names == 'Bob', 3]

array([ 0.3255302 , -1.40888628])

In [64]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [65]:
data[~(names=='Bob')]

array([[ 1.32618412, -0.01138557, -0.01409756,  0.5988489 ],
       [-0.00618896, -0.27795997,  0.30420328,  1.29108859],
       [-0.20374692,  0.45387091,  1.59509374,  0.60522322],
       [ 1.12400473,  0.40844548,  0.95931015, -1.17977155],
       [ 1.76644748, -0.38508707,  0.34254208,  1.53624934]])

In [66]:
data[data<0]=0

In [67]:
data

array([[0.416265  , 0.27712602, 1.53009909, 0.3255302 ],
       [1.32618412, 0.        , 0.        , 0.5988489 ],
       [0.        , 0.        , 0.30420328, 1.29108859],
       [0.        , 0.        , 1.03902066, 0.        ],
       [0.        , 0.45387091, 1.59509374, 0.60522322],
       [1.12400473, 0.40844548, 0.95931015, 0.        ],
       [1.76644748, 0.        , 0.34254208, 1.53624934]])

In [68]:
data[names != 'Joe'] = 7 

In [69]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.32618412, 0.        , 0.        , 0.5988489 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.12400473, 0.40844548, 0.95931015, 0.        ],
       [1.76644748, 0.        , 0.34254208, 1.53624934]])

In [70]:
arr = np.empty((8,4))

In [71]:
arr

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         4.94065646e-324],
       [             nan,              nan,  3.23790862e-319,
         0.00000000e+000],
       [ 5.41461255e-076,  1.93863099e+224, -3.29142434e-037,
        -7.37154986e+028],
       [ 7.41911170e-308,  1.61897012e-317,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000]])

In [72]:
for i in range(8):
    arr[i] = i

In [73]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])